spring.application.name=student-management
spring.datasource.url=${DB_URL:jdbc:mariadb://127.0.0.1:3306/studentdb?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:chedly}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect


# Server configuration :
server.address=0.0.0.0
server.port=8089
server.servlet.context-path=/student
sonar.projectKey=jenkins
sonar.host.url=http://localhost:9000
sonar.token=0b904a13b24cefa464ac5df4639abe4d8e0c403a
sonar.java.binaries=target/classes
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
# ===== EMAIL =====
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=saraghliss.2002@gmail.com
spring.mail.password=xsflznwjaratjkrg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
# ===== JWT =====
jwt.secret=${JWT_SECRET:StudentOpsDefaultSecretKeyForDevOnly2024}
jwt.expiration=86400000

# ===== OTP =====
otp.expiration=300
spring.profiles.active=dev
